name: github pages
on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      # Step 1 - Checkout repository
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      # Step 2 - Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      # Step 3 - Setup Node and Tone.js
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
      #    cache: 'npm'
      # - run: npm install
      # Step 4a - Cache Hugo modules
      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      # Step 4b - Build Hugo site
      - name: Build
        run: hugo --minify
      # Step 5 - Deploy to external repo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: alexk2037
          user_email: alex.kappen@learningmate.com
          publish_branch: gh-pages
          publish_dir: ./public
